use super::*;
#[test]
fn part1_num_of_xmas() {
    let example_input =
"....#.....
.........#
..........
..#.......
.......#..
..........
.#..^.....
........#.
#.........
......#...";
    assert_eq!(solve_part1(example_input), 41);
}

#[test]
fn part2_num_of_x_mas() {
  let example_input =
"....#.....
.........#
..........
..#.......
.......#..
..........
.#..^.....
........#.
#.........
......#...";
  assert_eq!(solve_part2(example_input), 9);
}