use super::*;
#[test]
fn part1_checked_tiles() {
    let example_input =
"....#.....
.........#
..........
..#.......
.......#..
..........
.#..^.....
........#.
#.........
......#...";
    assert_eq!(solve_part1(example_input), 41);
}

#[test]
fn part2_ways_to_get_guard_loop() {
  let example_input =
"....#.....
.........#
..........
..#.......
.......#..
..........
.#..^.....
........#.
#.........
......#...";
    assert_eq!(solve_part2(example_input), 6);
}
